import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Search from "./Searchbar";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className = "w-full h-full">
      <body className={inter.className}>
        <div className="flex flex-col gap-10 items-center p-6">
        < Search />
        </div>
        <div>{children}</div></body>
    </html>
  )
}
