version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./ddl:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  nextjs:
    image: nextjs-docker-test
    build:
      context: .
      dockerfile: /dockerfiles/next/Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"
      
  expressjs:
    image: expressjs-docker-test
    build:
      context: .
      dockerfile: /dockerfiles/express/Dockerfile
    volumes:
      - .:/app
    ports:
      - "6969:6969"
      - "7979:7979"
      - "8989:8989"

volumes:
  pgdata: