version: "3.9"
services:
  # webserver:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./app:/app
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./ddl:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nextjs-docker-postgres
  #   environment:
  #     - PORT=${PORT}
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./src:/app/
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nextjs-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - db
    
  nextjs:
    image: nextjs-docker-test
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"

  expressjs:
    image: expressjs-docker-test
    build:
      context: .
      dockerfile: Dockerfile.expressjs
    volumes:
      - .:/app
    ports:
      - "6969:6969"

volumes:
  pgdata:
